// ─── Design tokens voor Inkooporders feature (Emerald Light theme) ────────
// Gedeeld tussen src/pages/Inkooporders.tsx en src/components/inkooporders/*
export const T = {
  navy: "var(--bg-base)",
  surface: "var(--bg-surface)",
  surfaceBlur: "color-mix(in srgb, var(--bg-surface) 92%, transparent)",
  border: "var(--border-soft)",
  borderActive: "var(--accent-border)",
  text: "var(--text-primary)",
  textMuted: "var(--text-muted)",
  primary: "var(--accent)",
  primaryGradient: "linear-gradient(135deg, var(--accent), var(--accent-dark))",
  primarySoft: "var(--accent-light)",
  warn: "var(--warn-text)",
  warnSoft: "var(--warn-light)",
  warnBorder: "var(--warn-border)",
  info: "var(--info)",
  infoSoft: "var(--info-light, rgba(30,58,138,0.08))",
  infoBorder: "rgba(30,58,138,0.25)",
  danger: "var(--danger)",
  dangerSoft: "var(--danger-light)",
  dangerBorder: "rgba(185,28,28,0.25)",
  mono: "DM Mono, monospace",
  step: "var(--bg-surface-2)",
} as const;
